# camera configuration
camera:
  ip: 10.111.58.36
  password: gesti0narc0s
  port: 554
  user: admin
  fps: 20
# model configuration. Id detected
class_ids:
- 0   #person
- 2   #car
- 3   #motorcycle
- 5   #bus
- 7   #truck
# restaurant features.
restaurant:
  acronimo: MAI
  country: AR
# vehicle counting parameters.
vehicle_counting:
  automac_coordinates: [[0.28158844765342944, 0.25290697674418605], [0.6552346570397112,
      0.09883720930232558]]                                         # correspond to x1,y1 and x2,y2
  street_coordinates: [[0.6064981949458483, 0.3866279069767442], [0.6714801444043321,
      0.5988372093023255]]                                           # correspond to x1,y1 and x2,y2
