# camera configuration
camera:
  ip: 10.111.90.31
  password: Herm*2014ARGEN
  port: 554
  user: admin
  fps: 20
# model configuration. Id detected
class_ids:
- 0   #person
- 2   #car
- 3   #motorcycle
- 5   #bus
- 7   #truck
# restaurant features.
restaurant:
  acronimo: R26
  country: AR
# vehicle counting parameters.
vehicle_counting:
  automac_coordinates: [[0.5, 0.17732558139534885], [0.6028880866425993, 0.3226744186046512]] # correspond to x1,y1 and x2,y2
  street_coordinates: [[0.6353790613718412, 0.4011627906976744], [0.4007220216606498,
      0.43023255813953487]]                                          # correspond to x1,y1 and x2,y2
