# camera configuration
camera:
  ip: 10.111.153.31
  password: Herm*2014ARGEN
  port: 554
  user: admin
  fps: 20
# model configuration. Id detected
class_ids:
- 0   #person
- 2   #car
- 3   #motorcycle
- 5   #bus
- 7   #truck
# restaurant features.
restaurant:
  acronimo: CGP
  country: AR
# vehicle counting parameters.
vehicle_counting:
  automac_coordinates: [[0.24368231046931407, 0.5784883720930233], [0.4675090252707581,
      0.5872093023255814]]                                                                    # correspond to x1,y1 and x2,y2
  street_coordinates: [[0.7166064981949458, 0.7151162790697675], [0.6498194945848376,
      0.8081395348837209]]                                           # correspond to x1,y1 and x2,y2
