# camera configuration
camera:
  ip: 10.111.58.36
  password: gesti0narc0s
  port: 554
  user: admin
  fps: 20
# restaurant features.
restaurant:
  acronimo: MAI
  country: AR
  vehicle_counting:
    street_coordinates: [5, 6, 7, 8] # correspond to x1,y1 and x2,y2
