# camera configuration
camera:
  ip: 10.111.58.36
  password: gesti0narc0s
  port: 554
  user: admin
  fps: 20
# model configuration. Id detected
class_ids:
- 0   #person
- 2   #car
- 3   #motorcycle
- 5   #bus
- 7   #truck
# restaurant features.
restaurant:
  acronimo: MAI
  country: AR
# vehicle counting parameters.
vehicle_counting:
  automac_coordinates: [[0.301, 0.302], [0.649, 0.13]]              # correspond to x1,y1 and x2,y2
  street_coordinates: [[0.653, 0.373], [0.745, 0.562]]               # correspond to x1,y1 and x2,y2
